# Generated by Django 4.0.5 on 2023-07-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculomodel',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'vehiculo', 'verbose_name_plural': 'vehiculos'},
        ),
        migrations.AddField(
            model_name='vehiculomodel',
            name='clasificacion',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiculomodel',
            name='categoria',
            field=models.CharField(choices=[('Particular', 'Particular'), ('Transporte', 'Transporte'), ('Carga', 'Carga')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiculomodel',
            name='marca',
            field=models.CharField(choices=[('Chevrolet', 'Chevrolet'), ('Fiat', 'Fiat'), ('Ford', 'Ford'), ('Toyota', 'Toyota')], max_length=100),
        ),
    ]
