# Generated by Django 4.0.5 on 2023-07-14 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0003_alter_vehiculomodel_categoria_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculomodel',
            options={'ordering': ['-fecha_creacion'], 'permissions': (('visualizar_catalogo', 'Visualizar catálogo'),), 'verbose_name': 'vehiculo', 'verbose_name_plural': 'vehiculos'},
        ),
    ]
